info: {}
name: straight_heater_meander_5905ea56
settings:
  cross_section: strip
  extension_length: 15
  heater_taper_length: 10
  heater_width: 2.5
  layer_heater: HEATER
  length: 300
  radius: 5
  spacing: 2
  straight_widths:
  - 0.8
  - 0.9
  - 0.8
  taper_length: 10
  via_stack: via_stack_heater_mtop
