info: {}
name: die_with_pads_S11470_49_1695e6ce
settings:
  cross_section: strip
  edge_to_grating_distance: 150
  edge_to_pad_distance: 150
  grating_coupler: grating_coupler_te
  grating_pitch: 250
  layer_floorplan: 32
  ngratings: 14
  npads: 31
  pad: pad
  pad_pitch: 300
  size:
  - 11470
  - 4900
