info:
  route_info_length: 10
  route_info_type: xs_87fc063d
  route_info_weight: 10
  route_info_xs_87fc063d_length: 10
  route_info_xs_87fc063d_taper_length: 10
name: taper_cross_section_CSs_9478a791
settings:
  cross_section1: strip_rib_tip
  cross_section2: rib2
  length: 10
  linear: false
  npoints: 101
  width_type: parabolic
