info: {}
name: straight_pin_L500_CSpin_15abe242
settings:
  cross_section: pin
  length: 500
  taper: taper_strip_to_ridge
  via_stack: Fvia_stack_Mgdsfactorypcomponentspvia_stack_SLSLAB90_M1_M2_MTOP_Vviac_via1_via2_None
  via_stack_spacing: 2
  via_stack_width: 10
