info: {}
name: coh_tx_single_pol_BPSFa_4ee171aa
settings:
  balanced_phase_shifters: false
  cross_section: strip
  mzm: mzi_pin
  mzm_length: 200
  mzm_ps_spacing: 40
  mzm_y_spacing: 50
  pad_array: pad_array
  phase_shifter: straight_pin
  phase_shifter_length: 100
  splitter: mmi1x2
  xspacing: 40
