info: {}
name: cdsem_all_W0p4_0p45_0p5_ba26fb18
settings:
  bend90: bend_circular
  cross_section: strip
  dense_lines_gap: 0.3
  dense_lines_labels:
  - DL
  - DM
  - DH
  dense_lines_width: 0.3
  dense_lines_width_difference: 0.02
  spacing: 5
  straight: straight
  text: text_rectangular_mini
  widths:
  - 0.4
  - 0.45
  - 0.5
  - 0.6
  - 0.8
  - 1
