info: {}
name: greek_cross_with_pads_P_fa616bf3
settings:
  cross_section: Fcross_section_Mgdsfactorypcross_section_SLM1_W10_PNe1_e2_PTelectrical_electrical_RNone
  greek_cross_component: greek_cross
  pad: pad
  pad_spacing: 150
  pad_via: via_stack_m1_mtop
