info:
  dy: 10
  length: 16.637
  min_bend_radius: 7.061
  radius: 10
  route_info_length: 16.637
  route_info_min_bend_radius: 7.061
  route_info_n_bend_90: 1
  route_info_type: xs_34e31a19
  route_info_weight: 16.637
  route_info_xs_34e31a19_length: 16.637
name: add_trenches_Cbend_eule_0a7a1008
settings:
  component: bend_euler
  cross_section: rib_with_trenches
  layer_component: WG
  layer_trench: DEEP_ETCH
  left: 0
  top: 0
  width_trench: 2
